### ISSUE TITLE
crawling secretagentsnowman.com crashes extract and classify

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/cozyish#2]
```
crawler_1        | 172.22.0.1 - - [11/Oct/2019 04:49:02] "GET /?url=http://secretagentsnowman.com HTTP/1.1" 200 -
elasticsearch_1  | [2019-10-11T04:49:02,894][WARN ][o.e.c.r.a.DiskThresholdMonitor] [leq55HT] flood stage disk watermark [95%] exceeded on [leq55HT2ShuhkNupwNJ4tw][leq55HT][/usr/share/elasticsearch/data/nodes/0] free: 2.8gb[4.8%], all indices on this node will be marked read-only
extract_1        | unable to decode file
extract_1        | unable to decode file
extract_1        | unable to decode file
nsfw_api_1       | /usr/local/lib/python2.7/dist-packages/skimage/io/_io.py:49: UserWarning: `as_grey` has been deprecated in favor of `as_gray`
nsfw_api_1       |   warn('`as_grey` has been deprecated in favor of `as_gray`')
extract_1        | unable to decode file
classify_1       | panic: assignment to entry in nil map
classify_1       |
classify_1       | goroutine 40 [running]:
classify_1       | main.classify(0xc0001f0240, 0x9e, 0x9e)
classify_1       | 	/app/main.go:209 +0x6d7
classify_1       | main.main.func1(0xc0001ea180, 0xc000222000)
classify_1       | 	/app/main.go:121 +0x229
classify_1       | created by main.main
classify_1       | 	/app/main.go:114 +0x5ba
rabbitmq_1       | 2019-10-11 04:49:04.784 [warning] <0.627.0> closing AMQP connection <0.627.0> (172.22.0.10:38116 -> 172.22.0.4:5672, vhost: '/', user: 'user'):
rabbitmq_1       | client unexpectedly closed TCP connection
extract_1        | unable to decode file
cozyish_classify_1 exited with code 2
extract_1        | unable to decode file
extract_1        | exif: []
extract_1        | panic: assignment to entry in nil map
extract_1        |
extract_1        | goroutine 39 [running]:
extract_1        | main.extract(0xc0002bd6b0, 0x8f, 0x8f)
extract_1        | 	/app/main.go:272 +0xbb8
extract_1        | main.main.func1(0xc0001101e0, 0xc0001486c0)
extract_1        | 	/app/main.go:82 +0x229
extract_1        | created by main.main
extract_1        | 	/app/main.go:75 +0x3be
rabbitmq_1       | 2019-10-11 04:49:05.874 [warning] <0.597.0> closing AMQP connection <0.597.0> (172.22.0.8:36206 -> 172.22.0.4:5672, vhost: '/', user: 'user'):
rabbitmq_1       | client unexpectedly closed TCP connection
cozyish_extract_1 exited with code 2
```

**Comment by scottleedavis** [comment]
fixed
